FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path logger --features container

FROM debian:bullseye
EXPOSE 9000
COPY --from=builder /usr/local/cargo/bin/logger /usr/local/bin/logger
CMD ["logger"]
