FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path . --features container

FROM debian:bullseye
EXPOSE 8000
COPY --from=builder /usr/local/cargo/bin/server /usr/local/bin/server
COPY --from=builder /usr/local/cargo/bin/toolkit /usr/local/bin/toolkit
COPY --from=builder /usr/src/backend/static/ static/
CMD ["server"]
