FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path uploader --features container

FROM debian:bullseye
EXPOSE 9001
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates
COPY --from=builder /usr/local/cargo/bin/uploader /usr/local/bin/uploader
CMD ["uploader"]
