FROM rust:1-bullseye as builder
ADD common/ /usr/src/common/
ADD api/ /usr/src/api/
WORKDIR /usr/src/api/
RUN mv vendor.cargo .cargo
RUN cargo install --path . --features container

FROM debian:bullseye
EXPOSE 8000
COPY --from=builder /usr/local/cargo/bin/server /usr/local/bin/server
COPY --from=builder /usr/local/cargo/bin/toolkit /usr/local/bin/toolkit
COPY --from=builder /usr/src/api/static/ static/
CMD ["server"]
