FROM rust:1 as builder
ADD common/ /usr/src/common/
ADD logger/ /usr/src/logger/
WORKDIR /usr/src/logger/
RUN cargo install --path . --features container
RUN strip /usr/local/cargo/bin/logger

FROM debian:stable-slim
EXPOSE 9000
COPY --from=builder /usr/local/cargo/bin/logger /usr/local/bin/logger
CMD ["logger"]
