FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path logger --features container

FROM debian:bullseye
EXPOSE 9001
COPY --from=builder /usr/local/cargo/bin/uploader /usr/local/bin/uploader
CMD ["uploader"]
