FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path soon

FROM debian:bullseye
EXPOSE 8000
COPY --from=builder /usr/local/cargo/bin/soon /usr/local/bin/soon
COPY --from=builder /usr/src/backend/soon/static/ static/
CMD ["soon"]
