FROM rust:1-bullseye as builder
ADD backend/ /usr/src/backend/
WORKDIR /usr/src/backend/
RUN mv vendor.cargo .cargo
RUN cargo install --path mailer --features container

FROM debian:bullseye
EXPOSE 9100
COPY --from=builder /usr/local/cargo/bin/mailer /usr/local/bin/mailer
CMD ["mailer"]
