[package]
name = "uploader"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
bytes = "1.2.1"
chrono = "0.4.22"
common = { version = "0.1.0", path = "../common" }
futures-lite = "1.12.0"
once_cell = "1.15.0"
reqwest = "0.11.12"
rusty-s3 = "0.3.2"
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
ulid = "1.0.0"
url = "2.3.1"
uuid = "1.2.1"
warp = "0.3.3"
