[package]
name = "uploader"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
bytes = "1.4.0"
chrono = "0.4.26"
common = { version = "0.1.0", path = "../common" }
futures-lite = "1.13.0"
once_cell = "1.18.0"
reqwest = "0.11.18"
rusty-s3 = "0.4.1"
serde = { version = "1.0.171", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
ulid = "1.0.0"
url = "2.4.0"
uuid = "1.4.0"
warp = "0.3.5"
