[package]
name = "uploader"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
bytes = "1.3.0"
chrono = "0.4.23"
common = { version = "0.1.0", path = "../common" }
futures-lite = "1.12.0"
once_cell = "1.17.0"
reqwest = "0.11.14"
rusty-s3 = "0.3.3"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.2", features = ["full"] }
ulid = "1.0.0"
url = "2.3.1"
uuid = "1.2.2"
warp = "0.3.3"
