apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-api-deploy-beta
  labels:
    app: circuit-api-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circuit-api-beta
  template:
    metadata:
      labels:
        app: circuit-api-beta
    spec:
      containers:
      - name: circuit-api-beta
        image: scistarter/circuit-api:0.1.53
        ports:
        - containerPort: 8000
        env:
        - name: DOMAIN
          value: "sciencenearme.org"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret-beta
              key: DATABASE_URL
        - name: SUPERUSER_EMAIL
          valueFrom:
            secretKeyRef:
              name: superuser-secret-beta
              key: SUPERUSER_EMAIL
        - name: SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: superuser-secret-beta
              key: SUPERUSER_PASSWORD
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-beta
              key: JWT_SIGNING_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: circuit-api-service-beta
spec:
  selector:
    app: circuit-api-beta
  ports:
    - protocol: TCP
      port: 8000

