apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-collator-deploy
  labels:
    app: circuit-collator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circuit-collator
  template:
    metadata:
      labels:
        app: circuit-collator
    spec:
      containers:
      - name: circuit-collator
        image: scistarter/circuit-collator:0.1.20
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: ga4-access
          mountPath: "/etc/ga4"
          readOnly: true
        env:
        - name: OPENCAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: opencage
              key: OPENCAGE_API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret-beta
              key: DATABASE_URL
      volumes:
      - name: ga4-access
        secret:
          secretName: ga4
---
apiVersion: v1
kind: Service
metadata:
  name: circuit-collator-service
spec:
  selector:
    app: circuit-collator
  ports:
    - protocol: TCP
      port: 9000


