apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-frontend-deploy
  labels:
    app: circuit-frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: circuit-frontend
  template:
    metadata:
      labels:
        app: circuit-frontend
    spec:
      containers:
      - name: circuit-frontend
        image: scistarter/circuit-frontend:master-0.1.292
        ports:
        - containerPort: 3000
        env:
        - name: MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox
              key: MAPBOX_TOKEN
        - name: DOMAIN
          value: "sciencenearme.org"
---
apiVersion: v1
kind: Service
metadata:
  name: circuit-frontend-service
spec:
  selector:
    app: circuit-frontend
  ports:
    - protocol: TCP
      port: 3000
