apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-importer-deploy-beta
  labels:
    app: circuit-importer-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circuit-importer-beta
  template:
    metadata:
      labels:
        app: circuit-importer-beta
    spec:
      containers:
      - name: circuit-importer-beta
        image: scistarter/circuit-importer:0.1.93
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret-beta
              key: DATABASE_URL
        - name: SCIENCEWORKS_ORG_ID
          valueFrom:
            secretKeyRef:
              name: scienceworks-beta
              key: SCIENCEWORKS_ORG_ID
        - name: SCIENCEWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: scienceworks-beta
              key: SCIENCEWORKS_API_KEY
        - name: OPENCAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: opencage
              key: OPENCAGE_API_KEY
        - name: AIRTABLE_TOKEN
          valueFrom:
            secretKeyRef:
              name: airtable-beta
              key: AIRTABLE_TOKEN
        - name: UPLOADER_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: uploader-auth
              key: UPLOADER_AUTH_SECRET
