apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-beta
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
  - hosts:
      - beta.sciencenearme.org
    secretName: cert-beta
  rules:
  - host: beta.sciencenearme.org
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: circuit-api-service-beta
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: circuit-frontend-service-beta
            port:
              number: 3000
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daniel@arbuckle-everything.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class:  nginx
