[package]
name = "common"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
aho-corasick = "0.7.19"
ammonia = "3.2.1"
async-std = { version = "1.12.0", features = ["attributes"] }
chrono = { version = "0.4.22", features = ["serde"] }
chrono-tz = "0.6.3"
djangohashers = "1.5.9"
futures = "0.3.24"
hex = "0.4.3"
hmac = "0.12.1"
jwt = "0.16.0"
once_cell = "1.15.0"
readonly = "0.2.2"
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_repr = "0.1.9"
sha2 = "0.10.6"
sqlx = { version = "0.6.2", features = ["runtime-async-std-rustls", "postgres", "macros", "migrate", "uuid", "time", "json", "tls", "offline", "chrono"] }
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
thiserror = "1.0.37"
time = { version = "0.3.14", features = ["serde"] }
uuid = { version = "1.1.2", features = ["v4", "v5", "serde"] }
