[package]
name = "collator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.23"
common = { version = "0.1.0", path = "../common", default-features = false, features = ["tokio"] }
google-analyticsdata1_beta = "4.0.1"
reqwest = { version = "0.11.13", features = ["rustls-tls", "brotli", "gzip", "deflate"] }
rusty-s3 = "0.3.2"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "chrono", "postgres", "json", "uuid", "macros", "offline", "tls", "migrate"] }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.22.0", features = ["full"] }
