[package]
name = "collator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
common = { version = "0.1.0", path = "../common" }
google-analyticsdata1_beta = "4.0.1"
reqwest = { version = "0.11.13", features = ["rustls-tls", "brotli", "gzip", "deflate"] }
rusty-s3 = "0.3.2"
tokio = { version = "1.22.0", features = ["full"] }
