[package]
name = "common"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
chrono = { version = "0.4.19", features = ["serde"] }
djangohashers = "1.4.1"
futures = "0.3.16"
hex = "0.4.3"
hmac = "0.11.0"
jwt = "0.14.0"
once_cell = "1.7.2"
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.5"
sqlx = { version = "0.5.5", features = ["runtime-async-std-rustls", "postgres", "macros", "migrate", "uuid", "time", "json", "tls", "offline", "chrono"] }
strum = "0.21.0"
strum_macros = "0.21.1"
thiserror = "1.0.25"
uuid = { version = "0.8.2", features = ["v4", "v5", "serde"] }
