[package]
name = "common"
version = "0.1.0"
authors = ["Daniel Arbuckle <daniel@arbuckle-everything.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
djangohashers = "1.4.1"
hex = "0.4.3"
once_cell = "1.7.2"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.3"
sqlx = { version = "0.5.2", features = ["runtime-async-std-rustls", "postgres", "macros", "migrate", "uuid", "time", "json", "tls", "offline"] }
thiserror = "1.0.24"
time = { version = "0.2.26", features = ["serde"] }
uuid = { version = "0.8.2", features = ["v4", "v5", "serde"] }
