[package]
name = "importer"
version = "0.1.0"
authors = ["Daniel Arbuckle <djarb@highenergymagic.org>"]
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[lib]
name = "importer"
path = "src/lib.rs"

[[bin]]
name = "service"
path = "src/service.rs"

[dependencies]
common = { path = "../common" }
bytes = { version = "1.4.0", features = ["serde"] }
csv = "1.2.1"
ical = "0.7.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
ureq = { version = "2.6.2", features = ["json", "charset"] }
sqlx = "0.6.3"
async-std = "1.12.0"
async-trait = "0.1.68"
chrono = "0.4.24"
once_cell = "1.17.1"
uuid = "1.3.1"
http-auth-basic = "0.3.3"
chrono-tz = "0.8.2"
htmlentity = "1.3.1"
Inflector = "0.11.4"
regex = "1.7.3"
void = "1.0.2"
