[package]
name = "importer"
version = "0.1.0"
authors = ["Daniel Arbuckle <djarb@highenergymagic.org>"]
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[lib]
name = "importer"
path = "src/lib.rs"

[[bin]]
name = "service"
path = "src/service.rs"

[dependencies]
common = { path = "../common" }
bytes = { version = "1.2.1", features = ["serde"] }
csv = "1.1.6"
ical = "0.7.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
ureq = { version = "2.5.0", features = ["json", "charset"] }
sqlx = "0.6.2"
async-std = "1.12.0"
async-trait = "0.1.58"
chrono = "0.4.22"
once_cell = "1.15.0"
uuid = "1.2.1"
http-auth-basic = "0.3.3"
chrono-tz = "0.6.3"
htmlentity = "1.2.0"
Inflector = "0.11.4"
