[package]
name = "server"
version = "0.1.0"
authors = ["Daniel Arbuckle <djarb@highenergymagic.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
container = []

[dependencies]
askama = { version = "0.10.5", features = ["with-tide"] }
askama_tide = "0.13.0"
async-std = { version = "1.9.0", features = ["attributes"] }
djangohashers = "1.4.1"
hex = "0.4.3"
hmac = "0.10.1"
jwt = "0.13.0"
once_cell = "1.7.2"
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9.3"
sqlx = {version = "0.5.1", features = ["runtime-async-std-rustls", "postgres", "macros", "migrate", "uuid", "time", "json", "tls", "offline"] }
thiserror = "1.0.24"
tide = "0.16.0"
tide-fluent-routes = "0.1.5"
tide-sqlx = { version = "0.6.0", features = ["postgres", "rustls"] }
#tide-websockets = "0.3.0"
time = { version = "0.2.26", features = ["serde"] }
urlencoding = "1.1.1"
uuid = { version = "0.8.2", features = ["v4", "v5", "serde"] }
